## numpy -> numerical python
# Basics

In [2]:
import numpy as np
import time

In [3]:
arr_1d = np.array([1, 2, 3, 4, 4])
print("1D array:", arr_1d)

1D array: [1 2 3 4 4]


In [4]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


python vs numpy array

In [5]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1, 2, 3])
print("Python array multiplication ", np_array * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


In [6]:
start = time.time()
py_list = [x * 2 for x in range(1, 100000)]
print("\nList operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1, 100000) * 2
print("Array operation time: ", time.time() - start)



List operation time:  0.00492405891418457
Array operation time:  0.0006709098815917969


## Creating Array from scratch

In [7]:
zeros = np.zeros((4, 4))
print("Zeros array: \n", zeros)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
ones = np.ones((3, 4))
print("Ones Array: \n", ones)

Ones Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
full = np.full((2, 2), "k")
print("Constant Array: \n", full)

Constant Array: 
 [['k' 'k']
 ['k' 'k']]


In [10]:
random = np.random.random((2, 2))
print("Random Array: \n", random)

Random Array: 
 [[0.65860647 0.54096228]
 [0.92275888 0.93410941]]


In [11]:
sequence = np.arange(0, 11, 2)
print("Sequence Array: \n", sequence)

Sequence Array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix, Tensor

In [12]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]],
                    [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Prperties

In [13]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


In [14]:
### Array reshaping

arr = np.arange(12)
print("Original Array ", arr)

reshaped = arr.reshape((3, 4))
print("\nReshaped array \n", reshaped)

flattened = reshaped.flatten()
print("\nFlattened Array \n", flattened)


# ravel (returns view instead of copy)
raveled = reshaped.ravel()
print("\nRaveled Array \n", raveled)

# Transpose

transpose = reshaped.T
print("\nTransposed Array \n", transpose)

Original Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed Array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [15]:
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print(reshaped)

"""
#* Rule
total elements must stay the same
3 * 4 = 12
"""
print(arr.reshape(4,-1))

# -1 means NumPy calculates automatically

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## Flatten vs Ravel

In [16]:
flat = reshaped.flatten()
print(flat)
print(reshaped)
raveled = reshaped.ravel()
print(raveled)
print(reshaped)
raveled[0] = 100
print(reshaped) # Because they share same memory
print(flat.base)
print(raveled.base)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
None
[100   1   2   3   4   5   6   7   8   9  10  11]


In [17]:
# Random integer

arr = np.random.randint(1, 10, (3, 3))
print(arr)

# linspace
arr = np.linspace(0, 1, 5)
print(arr)

[[4 3 3]
 [8 6 8]
 [1 3 3]]
[0.   0.25 0.5  0.75 1.  ]


# Some problems from ChatGPT

In [18]:
# 1

arr = np.arange(1, 10)
reshaped = arr.reshape(3, 3)
print(reshaped)

# 2

transpose = reshaped.transpose()
print(transpose)

# 3
arr1 = np.array([10, 20, 30])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

result = arr1 + arr2
print(result)

# 4

column_mean = np.mean(result, axis=0)
print("\n", column_mean)

row_mean = np.mean(result, axis=1)
print(row_mean)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[11 22 33]
 [14 25 36]]

 [12.5 23.5 34.5]
[22. 25.]
