## Numpy Array Operations

In [2]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# *              0  1  2  3  4  5  6  7  8(-2)  9(-1)

print("Basic Slicing: ", arr[2:5])
print("With steps: ", arr[2 : len(arr) : 3])
print("Negative indexing: ", arr[-3])

Basic Slicing:  [3 4 5]
With steps:  [3 6 9]
Negative indexing:  8


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Specific element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire column: ", arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


## Sorting

In [3]:
unsorted = np.array([3, 1, 4, 2, 8, 5, 7, 6, 9])
print("Sorted Array", np.sort(unsorted))
print("Sorted Array", unsorted.sort())

Sorted Array [1 2 3 4 5 6 7 8 9]
Sorted Array None


In [5]:
arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])

print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by row", np.sort(arr_2d_unsorted, axis=1))


Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row [[1 3]
 [1 2]
 [2 3]]


## Filter

In [ ]:
numbers = np.array([x for x in range(1, 11)])
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers", even_numbers)

## Filter with mask

In [7]:
maks = numbers > 5
print("Numbers greater than 5 ", numbers[maks])

Numbers greater than 5  [ 6  7  8  9 10]


## Fancy indexing vs np.where

In [9]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [10]:
condition_array = np.where(numbers > 5, numbers * 4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


### Adding and Removing data

In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = arr1 + arr2
print(combined)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print("Combined array", combined)

[5 7 9]
Combined array [1 2 3 4 5 6]


### Array compatibility

In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

print("Compatibility shapes", arr1.shape == arr2.shape)

Compatibility shapes True


In [17]:
orignal = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((orignal, new_row)) #* Adds row

print(orignal)
print(with_new_row)

new_col = np.array([[7], [8], [9]])
with_new_col = np.hstack((with_new_row, new_col))
print("\n", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]

 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [20]:
arr = np.array([x for x in range(1, 11)])
deleted = np.delete(arr, 2)
print(deleted)

[ 1  2  4  5  6  7  8  9 10]
