##### Advanced indexing

In [2]:
import numpy as np

In [3]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[[0, 2, 4]])

arr2 = np.array([5, 12, 7, 3, 18, 10, 2, 15])

# * 1st, 4th and 7th elements
print(arr2[[0, 3, 6]])
print(arr2[[-1, -2, -3]])

[10 30 50]
[5 3 2]
[15  2 10]


##### Boolean Indexing

In [4]:
arr3 = np.arange(1, 11)

print(arr3 % 2 == 0)

[False  True False  True False  True False  True False  True]


In [5]:
# Filter Value
arr = np.array([5, 12, 7, 3, 18, 10, 2, 15])
print(arr[arr > 10])

# * values greater than 8
print(arr[arr > 8])

# * values less than 6
print(arr[arr < 6])

# * even numbers only
print(arr[arr % 2 == 0])


[12 18 15]
[12 18 10 15]
[5 3 2]
[12 18 10  2]


##### Modify Values with Conditions

In [6]:
arr[arr > 10] = 100
print(arr)

arr = np.array([5, 12, 7, 3, 18, 10, 2, 15])
# * numbers less than 5 → 0
arr[arr < 5] = 0
print(arr)

[  5 100   7   3 100  10   2 100]
[ 5 12  7  0 18 10  0 15]


In [7]:
dataset = np.array(["ID", "Jan", "Feb", "Mar"])
print(dataset)

sales = np.array(
    [
        [101, 20000, 22000, 25000], 
        [102, 18000, 21000, 24000], 
        [103, 25000, 26000, 28000]
    ]
)

#* 1 February Sales
feb_sales = sales[:, 2]
print("February sales: \n", feb_sales)

"""
rows : all
column : 2
"""

#* Total Sales of february
print(np.sum(feb_sales))

#* Sales of store 102
print(sales[1, 1:])

#* March Sales
print("March Sales: ", sales[:, 3])

#* Sales values (remove ID column)
print("\n", sales[:,1:])

['ID' 'Jan' 'Feb' 'Mar']
February sales: 
 [22000 21000 26000]
69000
[18000 21000 24000]
March Sales:  [25000 24000 28000]

 [[20000 22000 25000]
 [18000 21000 24000]
 [25000 26000 28000]]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

element = arr[1, 2]
print(element)

row = arr[0]
print(row)
col = arr[:, 0]
print(col)

6
[1 2 3]
[1 4]
