#####   Python lists are flexible — they can hold integers, strings, objects, even other lists, all mixed together. That flexibility has a cost: Python stores each element as a separate object in memory, scattered across RAM. To do math on a list, Python has to visit each object one by one.

#####   NumPy arrays (ndarray) make a deal: all elements must be the same type. In exchange, NumPy packs them into a single continuous block of memory — like a row of lockers side by side. Your CPU can then blast through that block at full speed using optimized C code, sometimes thousands of times faster than a Python loop.

In [31]:
import numpy as np

In [32]:
a = np.array([1, 2, 3, 4, 5])

print(np.zeros((3, 4)))
print(np.ones((3, 4)))
print(np.full((3, 4), 7))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [33]:
print(np.arange(2, 11, 2))

[ 2  4  6  8 10]


In [34]:
print(np.linspace(0, 1, 5))

print(np.random.random(3))
print(np.random.rand(3, 3))
print(np.random.randint(0, 10, (5, 5)))

[0.   0.25 0.5  0.75 1.  ]
[0.98777104 0.63212902 0.81961216]
[[0.25197874 0.84293136 0.98977751]
 [0.22013496 0.09415505 0.80976067]
 [0.41857841 0.41290496 0.47316236]]
[[0 9 1 7 7]
 [0 2 5 0 4]
 [6 3 0 3 0]
 [9 2 9 3 3]
 [6 7 3 7 2]]


In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.size)

(2, 3)
2
int64
6


In [36]:
arr = np.random.randint(2, 19, (3, 3))
print(arr[arr % 2 == 0])

arr1 = np.arange(2, 19, 2)
reshaped_arr1 = arr1.reshape(3, 3)
print("Reshaped Array: \n", reshaped_arr1)

print("Shape", reshaped_arr1.shape)
print("Dtype: ", reshaped_arr1.dtype)
row_sum = reshaped_arr1.sum(axis=1)
print("Row sums", row_sum)

[ 8 14  8  8  8 14]
Reshaped Array: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Shape (3, 3)
Dtype:  int64
Row sums [12 30 48]


In [37]:
# ndim - dimension
print(reshaped_arr1.ndim)  # 2
# shape - numbers of row and column
print(reshaped_arr1.shape)  # (3, 3)
lin = np.linspace(0, 1, 5)
print(lin)  # from 0 to 1 it will create 5 evenly spaced numbers
arr = np.arange(0, 1, 0.25)
print(arr)  # 1 is excluding value here
# and it adds up like this 0 + 0.25 = 0.25, 0.25 + 0.25 = 0.50

2
(3, 3)
[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75]


In [38]:
print(np.array([1, 2, 3]).dtype)  # int64
print(np.array([1, 2, 3.0]).dtype)  # float64 because there is a decimal point value
print(np.array([1, 2, "3"]).dtype)  # <u21
# unicode
# i think it's because of the values are stored in the same memory block and different
# data types takes diffrent space and also data type promotion which depands on the precision
# of data types int → float → complex → string (object)


int64
float64
<U21


In [39]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr[0])
print(arr[2, 1])
print(arr[-1, -1])

[10 20 30]
80
90


In [40]:
print(arr[0:2])
print(arr[:, 1])
print(arr[-1, -1])

[[10 20 30]
 [40 50 60]]
[20 50 80]
90


In [41]:
print(arr[0])
print("")
print(arr[:, 1])
print("")
print(arr[::-1])

[10 20 30]

[20 50 80]

[[70 80 90]
 [40 50 60]
 [10 20 30]]


In [42]:
arr = np.arange(9).reshape(3, 3)

view = arr[0:2]
view[0, 0] = 999  # Slicing gives a view same memory
print(arr)

print("")

copy = arr[0:2].copy()
copy[0, 0] = 0
print(arr)

[[999   1   2]
 [  3   4   5]
 [  6   7   8]]

[[999   1   2]
 [  3   4   5]
 [  6   7   8]]


In [43]:
arr = np.arange(12)

print(arr.reshape(3, 4))
print("")
print(arr.reshape(3, -1))  # -1 is wildcard
print(arr.reshape(3, 4).flatten())
print(arr.reshape(3, 4).T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
arr = np.arange(1, 26).reshape(5, 5)
print(arr)

print("3x3 sub-matrix from bottom-right", arr[-3:, -3:])
print("3rd column: ", arr[:, 2])
print("Reversed:", arr[::-1])

view = arr[0:3]
print("View: \n", view)
copied_array = arr.copy()
view[0:2] = 100
print("Slice is a view:\n", arr)
print("Original:\n", copied_array)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
3x3 sub-matrix from bottom-right [[13 14 15]
 [18 19 20]
 [23 24 25]]
3rd column:  [ 3  8 13 18 23]
Reversed: [[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
View: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Slice is a view:
 [[100 100 100 100 100]
 [100 100 100 100 100]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]]
Original:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [46]:
print("Shape change")
print(arr.shape)
arr = arr.reshape(1, -1)
print(arr.shape)

Shape change
(5, 5)
(1, 25)


In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
flattened = arr.flatten()
print("Original array: ", arr)
print("Flatten: ", flattened)

flattened[2] = 10000

print("Original array: ", arr)
print("Flatten: ", flattened)

raveled = arr.ravel()
print("Original array: ", arr)
print("Raveled: ", raveled)

raveled[2] = 1000  # ravel (returns view instead of copy)

print("Original array: ", arr)
print("Raveled: ", raveled)


Original array:  [[10 20 30]
 [40 50 60]
 [70 80 90]]
Flatten:  [10 20 30 40 50 60 70 80 90]
Original array:  [[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Flatten:  [   10    20 10000    40    50    60    70    80    90]
Original array:  [[10 20 30]
 [40 50 60]
 [70 80 90]]
Raveled:  [10 20 30 40 50 60 70 80 90]
Original array:  [[  10   20 1000]
 [  40   50   60]
 [  70   80   90]]
Raveled:  [  10   20 1000   40   50   60   70   80   90]


In [63]:
arr = np.arange(1, 25).reshape(4, 6)
print(arr)
print(arr.shape)
transposed = arr.T
print(transposed.shape)

arr = arr.reshape(24, -1)
print(arr.shape)
arr = arr.reshape(-1, 24)
print(arr.shape)
arr = arr.reshape(4, -1)
print(arr.shape)
arr = arr.reshape(-1, 4)
print(arr.shape)
arr = arr.reshape(3, -1)
print(arr.shape)
arr = arr.reshape(-1, 3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
(4, 6)
(6, 4)
(24, 1)
(1, 24)
(4, 6)
(6, 4)
(3, 8)


In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr[:, 1]) # NumPy drops dimension because there is only one axis

[20 50 80]
