##### Math Operations

In [34]:
import numpy as np

In [35]:
result = []
for x in [x**2 for x in range(1, 11)]:
    result.append(x)

In [36]:
arr = np.arange(1, 11)
result = arr**2

#### Vectorized Math Functions (Universal Functions (unfuncs))

In [37]:
arr = np.arange(1, 11, dtype=float) ** 2
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))

print("\n")

print(np.abs(arr))
print(np.round(arr, 2))
print(np.clip(arr, 2, 10))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15 1.90734657e+21 6.23514908e+27
 1.50609731e+35 2.68811714e+43]
[0.         1.38629436 2.19722458 2.77258872 3.21887582 3.58351894
 3.8918203  4.15888308 4.39444915 4.60517019]


[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]
[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]
[ 2.  4.  9. 10. 10. 10. 10. 10. 10. 10.]


In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.sum())
print(arr.mean())
print(arr.min())
print(arr.max())
print(arr.std())
print(arr.var())
print(np.median(arr))

45
5.0
1
9
2.581988897471611
6.666666666666667
5.0


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)
print(arr.sum(axis=0))  # column
print(arr.sum(axis=1))  # row

# axis=0 → operation runs down the columns (rows disappear)
# axis=1 → operation runs across the rows (columns disappear)

(2, 3)
[5 7 9]
[ 6 15]


In [40]:
print(arr.shape)
print(arr.sum(axis=0))
print(arr.sum(axis=1))
print(arr.sum())


(2, 3)
[5 7 9]
[ 6 15]
21


In [41]:
print(arr.sum(axis=1))
print(arr.sum(axis=1, keepdims=True))
print(arr.sum(axis=1).shape)
print(arr.sum(axis=1, keepdims=True).shape)

arr2 = np.array([1, 2, 3])
print(arr2.shape)

[ 6 15]
[[ 6]
 [15]]
(2,)
(2, 1)
(3,)


In [42]:
row_sums = arr.sum(axis=1, keepdims=True)
print(row_sums.shape)
normalised = arr / row_sums
print(np.round(normalised, 2))

(2, 1)
[[0.17 0.33 0.5 ]
 [0.27 0.33 0.4 ]]


In [ ]:
arr = np.random.seed(52)
print(arr)  # None
# Same seed same sequence
# Different seed different sequence
# Use for weight initialization in ANN

arr = np.random.randint(
    1, 20, (4, 4)
)  # This will change in every run if we remove seed
print(arr)

sum_array = np.sum(arr)
print(sum_array)

mean = np.mean(arr)
print(mean)

std = np.std(arr)
print(std)

column_max = np.max(arr, axis=0)
print(column_max)

row_min = np.min(arr, axis=1)
print(row_min)

None
[[12 14  1  6]
 [11 12  4  4]
 [ 2  4  2  6]
 [18 17 12 17]]
142
8.875
5.6995065575889985
[18 17 12 17]
[ 1  4  2 12]


In [ ]:
arr = np.random.randint(1, 20, (4, 4))
# This will change every time as there is no seed
result = (arr - arr.min()) / (arr.max() - arr.min())
print(result)

data = np.array([[1, 2, 3], [4, 5, 6]])

row_min = data.min(axis=1, keepdims=True)
row_max = data.max(axis=1, keepdims=True)

normalised = (data - row_min) / (row_max - row_min)
print(normalised)

arr = np.arange(1, 17).reshape(4, 4)
print(arr.sum(axis=0).shape)

# * Difference between arr.std() and arr.std(axis=0)
arr = [
    [2, 2, 2, 2, 2],
    [15, 6, 27, 8, 2],
    [
        23,
        2,
        54,
        1,
        2,
    ],
    [11, 44, 34, 7, 2],
]

print("Whole array:", np.std(arr))
print("Along axis 0:", np.std(arr, axis=0))  # top to down std(column)

[[0.52941176 0.88235294 0.         0.11764706]
 [0.35294118 0.76470588 0.35294118 0.94117647]
 [0.58823529 0.29411765 0.58823529 0.        ]
 [0.52941176 0.70588235 1.         0.52941176]]
[[0.  0.5 1. ]
 [0.  0.5 1. ]]
(4,)
Whole array: 15.3668474320532
Along axis 0: [ 7.56224173 17.68473918 18.59267329  3.04138127  0.        ]


### Normalization

##### Normalizing an array in NumPy refers to the process of scaling its values to a specific range, typically between 0 and 1. For example, an array like [1, 2, 4, 8, 10] can be normalized to [0.0, 0.125, 0.375, 0.875, 1.0], where the smallest value becomes 0, the largest becomes 1 and all other values are scaled proportionally in between. Let's explore different methods to perform this efficiently.

In [45]:
# Min-Max Normalization

a = np.array([1, 2, 4, 8, 10], dtype=float)

res = (a - a.min()) / (a.max() - a.min())
print(res.tolist())

[0.0, 0.1111111111111111, 0.3333333333333333, 0.7777777777777778, 1.0]


In [53]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

f = a.flatten()
n = (f - f.min()) / (f.max() - f.min())

result = n.reshape(a.shape)
print(result.tolist())
print(type(result.tolist()))


n = (a - a.min()) / (a.max() - a.min())
print(n)

[[0.0, 0.125, 0.25], [0.375, 0.5, 0.625], [0.75, 0.875, 1.0]]
<class 'list'>
[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


In [47]:
# Z-Score standardization

data = np.array([10, 20, 30, 40, 50, 60])

standardized = (data - data.mean()) / data.std()
print(standardized)

[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [48]:
# L2 Normalization
data = np.array([3.0, 4.0])

l2_normalized = data / np.linalg.norm(data)
print(l2_normalized)

[0.6 0.8]


In [50]:
# Normalizing Along an Axis (2D arrays)
data = np.array([[1, 2, 3], [4, 5, 6]])

row_min = data.min(axis=1, keepdims=True)
row_max = data.max(axis=1, keepdims=True)

normalised = (data - row_min) / (row_max - row_min)
print(normalised)

[[0.  0.5 1. ]
 [0.  0.5 1. ]]


In [52]:
data = np.array([[2, 8, 1], [4, 2, 6], [6, 5, 3]])

max_col = data.max(axis=0, keepdims=True)
min_col = data.min(axis=0, keepdims=True)

normalised = (data - min_col) / (max_col - min_col)
print(normalised)

[[0.  1.  0. ]
 [0.5 0.  1. ]
 [1.  0.5 0.4]]


In [ ]:
np.random.seed(52)
arr = np.random.randint(1, 17, (4, 4))
print(arr)
np.random.seed(42)
arr = np.random.randint(1, 17, (4, 4))
print(arr)

"""
# Respective output
[[ 6 13 12 14]
 [ 8  7 13  8]
 [ 1  6 11 12]
 [12 11  4  4]]
[[ 7  4 13 15]
 [11  8 13  5]
 [ 7 10  3  7]
 [11 11  8  5]]
"""
# i think it's because of algorithm and the arg is the starting point of it

arr = np.array(
    [
        [6, 13, 12, 14],
        [
            8,
            7, # ruff did this
            13,
            8,
        ],
        [1, 6, 11, 12],
        [12, 11, 4, 4],
    ]
)
print("row wise std:", np.std(arr, axis=1))
print("col wise std:", np.std(arr, axis=0))

# Min-MaxValues: need to be in [0,1]; no outliers
# Z-Score: Data is roughly Gaussian; ML algorithms
# L2 Norm: Direction matters more than magnitude (NLP, KNN)

# i have to google a bit for these topics but it was worth while

[[ 6 13 12 14]
 [ 8  7 13  8]
 [ 1  6 11 12]
 [12 11  4  4]]
[[ 7  4 13 15]
 [11  8 13  5]
 [ 7 10  3  7]
 [11 11  8  5]]
row wise std: [3.1124749  2.34520788 4.38748219 3.76662979]
col wise std: [3.96074488 2.86138079 3.53553391 3.84057287]
