#### Boolean Indexing

In [2]:
import numpy as np

In [3]:
arr = np.array([10, 25, 3, 47, 8, 19])

mask = arr > 15
print(mask) # True/False

print(arr[mask]) # [25 47 19]

[False  True False  True False  True]
[25 47 19]


In [4]:
print(arr[arr > 15])

[25 47 19]


In [5]:
arr =  np.array([10, 25, 3, 47, 8, 19])

# and -> &
print(arr[(arr > 5) & (arr < 20)])

# or -> |
print(arr[(arr < 5) | (arr > 40)])

# not -> ~
print(arr[~(arr > 15)])
# never and, or, not. Python's keywords don't work element-wise on arrays.

[10  8 19]
[ 3 47]
[10  3  8]


In [6]:
# np.where(condition, value_if_true, value_if_false)

arr = np.array([1, -2, 3, -4, 5])

result = np.where(arr > 0, arr, 0)
print(result)

[1 0 3 0 5]


In [7]:
def relu(x):
    return np.where(x > 0, x, 0)


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr + 10)
print(arr * np.array([1, 2, 3]))
print((arr * np.array([1, 2, 3])).shape)

[[11 12 13]
 [14 15 16]]
[[ 1  4  9]
 [ 4 10 18]]
(2, 3)


In [9]:
# The broadcasting rules
'''
arr:    (2, 3)
scale:     (3,)   → treated as (1, 3) → stretched to (2, 3) ✅

arr:    (2, 3)
col:    (2, 1)    → stretched to (2, 3) ✅

arr:    (2, 3)
bad:    (2, 2)    → 3 ≠ 2, neither is 1 → ERROR ❌

dimensions are compatible if they're equal, or one of them is 1

'''


"\narr:    (2, 3)\nscale:     (3,)   → treated as (1, 3) → stretched to (2, 3) ✅\n\narr:    (2, 3)\ncol:    (2, 1)    → stretched to (2, 3) ✅\n\narr:    (2, 3)\nbad:    (2, 2)    → 3 ≠ 2, neither is 1 → ERROR ❌\n\ndimensions are compatible if they're equal, or one of them is 1\n\n"

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

col_mean = arr.mean(axis=0)  
print(col_mean.shape)
centered = arr - col_mean  
print(centered)
print(centered.shape)

row_mean = arr.mean(axis=1, keepdims=True)
print(row_mean)
centered = arr - row_mean
print(centered)

(3,)
[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]
(2, 3)
[[2.]
 [5.]]
[[-1.  0.  1.]
 [-1.  0.  1.]]


In [ ]:
np.random.seed(0)

arr = np.random.randint(-10, 20, (5, 5))
print(arr)

mask = arr > 0 # ja bola hoyeche seta korai valo
# besi barabari valo noi
print(arr[mask]) 

print(np.where(arr < 0, 0, arr))

mean = arr.mean()
print(mean)
print(np.where(arr > mean, 1, 0))

row_mean = arr.mean(axis=1, keepdims=True)
centered = arr - row_mean
print(centered)

row_sum = arr.sum(axis=1, keepdims=True)
print("Array: ", arr)
result = arr / row_sum
print("Result:", result)
print(result.sum(axis=1)) # clip or take absolute values first

# because of conflict and python keywords dont work element-wise on arrays
# @2

arr = np.arange(1, 13).reshape(4, 3)
vec = arr.mean(axis=1)
print(arr.shape)
print(vec) 
print(vec.shape)
# Two dimensions are not equal (4, 3) != (4, )
# but we can use keepdims

# np.where(x > 0, x, 0) is activision function (rectified linear unit or ReLU)
# is used in nural network to learn non linear relations in ML


[[  2   5  11 -10  -7]
 [ 17  -7  -3  -1   9]
 [ 11   8  -6  13  -4]
 [ 14  14   2  16  -9]
 [ -4  -3  13   4  14]]
[ 2  5 11 17  9 11  8 13 14 14  2 16 13  4 14]
[[ 2  5 11  0  0]
 [17  0  0  0  9]
 [11  8  0 13  0]
 [14 14  2 16  0]
 [ 0  0 13  4 14]]
3.96
[[0 1 1 0 0]
 [1 0 0 0 1]
 [1 1 0 1 0]
 [1 1 0 1 0]
 [0 0 1 1 1]]
[[  1.8   4.8  10.8 -10.2  -7.2]
 [ 14.  -10.   -6.   -4.    6. ]
 [  6.6   3.6 -10.4   8.6  -8.4]
 [  6.6   6.6  -5.4   8.6 -16.4]
 [ -8.8  -7.8   8.2  -0.8   9.2]]
Array:  [[  2   5  11 -10  -7]
 [ 17  -7  -3  -1   9]
 [ 11   8  -6  13  -4]
 [ 14  14   2  16  -9]
 [ -4  -3  13   4  14]]
Result: [[  2.           5.          11.         -10.          -7.        ]
 [  1.13333333  -0.46666667  -0.2         -0.06666667   0.6       ]
 [  0.5          0.36363636  -0.27272727   0.59090909  -0.18181818]
 [  0.37837838   0.37837838   0.05405405   0.43243243  -0.24324324]
 [ -0.16666667  -0.125        0.54166667   0.16666667   0.58333333]]
[1. 1. 1. 1. 1.]
(4, 3)
[ 2.  5.  8.