#### Boolean Indexing

In [1]:
import numpy as np

In [ ]:
arr = np.array([10, 25, 3, 47, 8, 19])

mask = arr > 15
print(mask) # True/False

print(arr[mask]) # [25 47 19]

[False  True False  True False  True]
[25 47 19]


In [3]:
print(arr[arr > 15])

[25 47 19]


In [ ]:
arr =  np.array([10, 25, 3, 47, 8, 19])

# and -> &
print(arr[(arr > 5) & (arr < 20)])

# or -> |
print(arr[(arr < 5) | (arr > 40)])

# not -> ~
print(arr[~(arr > 15)])
# never and, or, not. Python's keywords don't work element-wise on arrays.

[10  8 19]
[ 3 47]
[10  3  8]


In [7]:
# np.where(condition, value_if_true, value_if_false)

arr = np.array([1, -2, 3, -4, 5])

result = np.where(arr > 0, arr, 0)
print(result)

[1 0 3 0 5]


In [8]:
def relu(x):
    return np.where(x > 0, x, 0)


In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr + 10)
print(arr * np.array([1, 2, 3]))
print((arr * np.array([1, 2, 3])).shape)

[[11 12 13]
 [14 15 16]]
[[ 1  4  9]
 [ 4 10 18]]
(2, 3)


In [13]:
# The broadcasting rules
'''
arr:    (2, 3)
scale:     (3,)   → treated as (1, 3) → stretched to (2, 3) ✅

arr:    (2, 3)
col:    (2, 1)    → stretched to (2, 3) ✅

arr:    (2, 3)
bad:    (2, 2)    → 3 ≠ 2, neither is 1 → ERROR ❌

dimensions are compatible if they're equal, or one of them is 1

'''


"\narr:    (2, 3)\nscale:     (3,)   → treated as (1, 3) → stretched to (2, 3) ✅\n\narr:    (2, 3)\ncol:    (2, 1)    → stretched to (2, 3) ✅\n\narr:    (2, 3)\nbad:    (2, 2)    → 3 ≠ 2, neither is 1 → ERROR ❌\n\ndimensions are compatible if they're equal, or one of them is 1\n\n"

In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

col_mean = arr.mean(axis=0)  
print(col_mean.shape)
centered = arr - col_mean  
print(centered)
print(centered.shape)

row_mean = arr.mean(axis=1, keepdims=True)
print(row_mean)
centered = arr - row_mean
print(centered)

(3,)
[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]
(2, 3)
[[2.]
 [5.]]
[[-1.  0.  1.]
 [-1.  0.  1.]]
