#### Linear Algebra + Stacking & Splitting

In [1]:
import numpy as  np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))

arr1 = np.array([[1, 2], [4, 5]])
arr2 = np.array([[7, 8], [10, 11]])
print(arr1 @ arr2)

# (m, n) @ (n, p) -> (m, p)

"""
(3, 4) @ (4, 5) → (3, 5)  ✅
(3, 4) @ (3, 5) → ERROR   ❌  4 ≠ 3
```

---

### Why this is neural networks

A single neural network layer is literally:
```
output = activation(inputs @ weights + bias)
"""

32
[[27 30]
 [78 87]]


'\n(3, 4) @ (4, 5) → (3, 5)  ✅\n(3, 4) @ (3, 5) → ERROR   ❌  4 ≠ 3\n```\n\n---\n\n### Why this is neural networks\n\nA single neural network layer is literally:\n```\noutput = activation(inputs @ weights + bias)\n'

In [ ]:
inputs = np.random.randn(5, 3) # 5 samples, 3 features
weights = np.random.randn(3, 4) # 3 inputs 4 -> neurons
bies = np.random.randn(4) # one bies per neuron

raw = inputs @ weights + bies # shape -> (5, 4)
output = np.where(raw > 0, raw, 0) # ReLU
print(raw)
print(output)

[[ 1.23656716  0.79723265  0.80157855  0.86540274]
 [ 2.72781161  0.62481017 -0.25985612 -0.57455326]
 [ 1.28808     1.4738344   0.84266569 -0.37078354]
 [ 2.44281403  1.14970483  0.19087622 -0.76522969]
 [ 1.06252148  1.17370212  0.91768391  0.31590935]]
[[1.23656716 0.79723265 0.80157855 0.86540274]
 [2.72781161 0.62481017 0.         0.        ]
 [1.28808    1.4738344  0.84266569 0.        ]
 [2.44281403 1.14970483 0.19087622 0.        ]
 [1.06252148 1.17370212 0.91768391 0.31590935]]


In [4]:
arr = np.array([[1, 2], [3, 4]], dtype=float)

print(np.linalg.norm(arr))
print(np.linalg.det(arr))
print(np.linalg.inv(arr))
print(arr @ (np.linalg.inv(arr)))
print(np.linalg.eig(arr))

5.477225575051661
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [5]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(np.vstack([arr1, arr2])) # (4, 2)
print(np.hstack([arr1, arr2])) # (2, 4)

print(np.concatenate([arr1, arr2], axis=0)) # (4, 2)
print(np.concatenate([arr1, arr2], axis=1)) # (2, 4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [6]:
arr = np.arange(1, 25).reshape(4, 6)

print(np.split(arr, 2, axis=0))
print(np.hsplit(arr, 3))
print(np.vsplit(arr, 4))

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]
[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]
[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]


In [25]:
np.random.seed(0)

inputs = np.random.randn(6, 4)
w1 = np.random.randn(4, 5)
b1 = np.random.randn(5)
w2 = np.random.randn(5, 3)
b2 = np.random.randn(3)

raw1 = inputs @ w1 + b1
print(raw1.shape)
output1 = np.where(raw1 > 0, raw1, 0)
print(output1.shape)

raw2 = output1 @ w2 + b2
print(raw2)
print(raw2.shape)

output0 = raw2[:, 0]
best = np.argmax(output0) # return index
print(best)


l2 = output1 / np.linalg.norm(output1, axis=1, keepdims= True)
print(l2)

stacked = np.vstack([inputs, inputs])

forward_pass1 = stacked @ w1 + b1
layer_1_output = np.where(forward_pass1 >0, forward_pass1, 0)
forward_pass = layer_1_output @ w2 + b2
print(forward_pass)
print(forward_pass.shape)

# (6, 4) @ (4, 5) = (6, 5)
"""
#? Lets take a small example
|-       -|     |-      -|   |-                                      -|
| 1  2  3 |     | 7  8   |   | 1*7 + 2*9 + 3*11      1*8 + 2*10 + 3*12|
|         | X   | 9  10  | = |                                        |
| 4  5  6 |     | 11 12  |   | 4*7 + 5*9 + 6*11      4*8 + 5*10 + 6*12|
|-       -|     |-      -|   |-                                      -|
           (2, 3)         (3, 2)                                      (2, 2)
"""
# Output layer activations should be close to linear, whereas hidden layer activations can be much more non-linear. ReLU is ideally suited for non-linear activations.
#! I had to use Quora for this

""""
inputs = np.random.randn(6, 4)
#? w1 = np.random.randn(5, 4)
b1 = np.random.randn(5)
w2 = np.random.randn(5, 3)
b2 = np.random.randn(3)

raw1 = inputs @ w1 + b1 #! ValueError
# Matrix multiplication requires the number of columns in the first matrix to equal the number of rows in the second
print(raw1.shape)
output1 = np.where(raw1 > 0, raw1, 0)
print(output1.shape)"""

(6, 5)
(6, 5)
[[-2.0168813  -6.63400432 -7.84993837]
 [-2.86658733 -5.22840802 -7.01844571]
 [ 0.10704454 -0.56095222 -1.96811371]
 [-0.37704012 -1.6019314  -1.51908933]
 [-1.85380504 -3.73531122 -2.16294094]
 [-3.47831457 -6.48122628 -3.45461868]]
(6, 3)
2
[[0.58126696 0.         0.         0.         0.81371293]
 [0.4779446  0.         0.         0.64158407 0.59994903]
 [0.         0.         0.         0.         1.        ]
 [0.91847906 0.         0.         0.39546961 0.        ]
 [0.73257289 0.         0.09017946 0.67468854 0.        ]
 [0.         0.80669034 0.18711093 0.56057131 0.        ]]
[[-2.0168813  -6.63400432 -7.84993837]
 [-2.86658733 -5.22840802 -7.01844571]
 [ 0.10704454 -0.56095222 -1.96811371]
 [-0.37704012 -1.6019314  -1.51908933]
 [-1.85380504 -3.73531122 -2.16294094]
 [-3.47831457 -6.48122628 -3.45461868]
 [-2.0168813  -6.63400432 -7.84993837]
 [-2.86658733 -5.22840802 -7.01844571]
 [ 0.10704454 -0.56095222 -1.96811371]
 [-0.37704012 -1.6019314  -1.51908933]
 [-

'"\ninputs = np.random.randn(6, 4)\n#? w1 = np.random.randn(5, 4)\nb1 = np.random.randn(5)\nw2 = np.random.randn(5, 3)\nb2 = np.random.randn(3)\n\nraw1 = inputs @ w1 + b1 #! ValueError\n# Matrix multiplication requires the number of columns in the first matrix to equal the number of rows in the second\nprint(raw1.shape)\noutput1 = np.where(raw1 > 0, raw1, 0)\nprint(output1.shape)'